import { BusinessUnit, User, Patient, Tutor, Product, Budget } from "@/domain";

export type Bill = {
  id: string;
  bill_date: Date;
  product_value: number;
  service_value: number;
  discount_value: number;
  fee_value: number | null;
  delivery_value: number;
  total_value: number;
  icms_base: number;
  icms_value: number;
  icms_st_base: number;
  icms_st_value: number;
  iss_base: number;
  iss_value: number;
  pis_base: number;
  pis_value: number;
  pis_retention_value: number;
  cofins_base: number;
  cofins_value: number;
  cofins_retention_value: number;
  ipi_base: number;
  ipi_value: number;
  icms_deferred_value: number;
  icms_fcp_value: number;
  icms_uf_origin_value: number;
  icms_uf_destination_value: number;
  other_value: number;
  additional_information: number;
  cancelled_at: Date | null;
  cancellation_observation: null | string;
  status: "BAIXADA" | "ABERTA";
  document_status: "Gerados" | null;
  created_at: Date;
  updated_at: Date;
  tag: string;
  closing_date: Date;
  paid_value: number;
  businessUnit: BusinessUnit;
  financialResponsible: {
    id: User["id"];
    name: User["user"]["name"];
  };
  seller: User;
  user: User["user"];
  patient: Patient;
  payments: {
    id: string;
    block: number;
    expiration_date: Date;
    fee_type: "SEM_JUROS";
    fee_value: number;
    fee_percentage: number;
    installment_value: number;
    total_value: number;
    status: null;
    created_at: Date;
    updated_at: Date;
    installments: number;
    nsu_document: 1;
    payment_method_discount_percentage: 0;
    payment_method_discount_value: 0;
    conference_date: null;
    qty_installments: 1;
    acquirer: {
      id: string;
      description: string;
    };
    flag: {
      id: string;
      description: string;
      code: string;
      type: "D" | "C" | "A";
    };
    paymentMethod: {
      id: string;
      description: string;
      requires_document: boolean;
      tef: "POS";
      type: "DEBITO" | "CREDITO";
      fee: number;
      automatic_cancellation: boolean;
      days_first_installment: number;
      days_between_installments: number;
      days_until_transfer: number;
      installments_without_password: number;
      max_installments: number;
      allow_change_expiration_date: boolean;
      minimum_installment_value: number;
      active: boolean;
      created_at: Date;
      updated_at: Date;
      usage: "RECEBER";
      nfe_code: string;
    };
  }[];
  client: Tutor;
  items: Product[];
  budget: {
    id: Budget["id"];
  };
};
